Repository sdtrdev/code-review, pull requests merged in 2020-12, with the labels that each got.

#2 docs: add language folders
  yazilim-dilleri/assembly/README.md
  yazilim-dilleri/c/README.md
  yazilim-dilleri/cplusplus/README.md
  yazilim-dilleri/csharp/README.md
  yazilim-dilleri/dart/README.md
  yazilim-dilleri/go/README.md
  yazilim-dilleri/java/README.md
  yazilim-dilleri/kotlin/README.md
  yazilim-dilleri/lua/README.md
  yazilim-dilleri/matlab/README.md
  yazilim-dilleri/other/README.md
  yazilim-dilleri/python/README.md
  yazilim-dilleri/r/README.md
  yazilim-dilleri/ruby/README.md
  yazilim-dilleri/rust/README.md
  yazilim-dilleri/swift/README.md
Labels: PR: reviewed-approved, enhancement

#3 add: new test file
  yazilim-dilleri/c/test.c
Labels: PR: reviewed-approved, help wanted

#8 PR icin aciklamalar.
  README.md
Labels: PR: reviewed-approved
